server:
  port: 8080

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: flight-service
        uri: lb://FLIGHT-SERVICE
        predicates:
          - Path=/flights/**
        filters:
          - name: CircuitBreaker
            args:
              name: flightServiceCircuitBreaker
              fallbackUri: forward:/fallback/flights

      - id: booking-service
        uri: lb://BOOKING-SERVICE
        predicates:
          - Path=/bookings/**
        filters:
          - name: CircuitBreaker
            args:
              name: bookingServiceCircuitBreaker
              fallbackUri: forward:/fallback/bookings

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  metrics:
    binders:
      system: false
