server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # Since it's a server, it doesn't register itself
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
