version: '3.8'
services:
  # ============== DATABASES ==============
  postgresql:
    container_name: flight_db
    image: postgres:15
    environment:
      POSTGRES_DB: flight_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: mongo_express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=flightAttendedUserMongoExpress
      - ME_CONFIG_MONGODB_ADMINPASSWORD=flightAttendedUserMongoExpress
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped

  # ============== MICROSERVICES ==============
  config-server:
    container_name: config-server
    image: config-server:1.0
    networks:
      - microservices-net
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - MANAGEMENT_METRICS_BINDERS_SYSTEM=false
    depends_on:
      - postgresql

  discovery-service:
    container_name: discovery-service
    image: discovery-service:1.0
    networks:
      - microservices-net
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MANAGEMENT_METRICS_BINDERS_SYSTEM=false
    depends_on:
      - config-server

  api-gateway:
    container_name: api-gateway
    image: api-gateway:1.0
    networks:
      - microservices-net
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MANAGEMENT_METRICS_BINDERS_SYSTEM=false
    depends_on:
      - discovery-service
      - config-server

  flight-service:
    container_name: flight-service
    image: flight-service:1.0
    networks:
      - microservices-net
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MANAGEMENT_METRICS_BINDERS_SYSTEM=false
    depends_on:
      - discovery-service
      - config-server
      - postgresql

networks:
  microservices-net:
    driver: bridge