server:
  port: 8081

spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Prevents Hibernate from overriding schema.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always # Ensures schema.sql and data.sql are always loaded